In [0]:
# Adapted from
# https://github.com/keras-team/keras/blob/master/examples/addition_rnn.py

In [0]:
import warnings
warnings.filterwarnings('ignore')

In [54]:
%matplotlib inline
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [55]:
import tensorflow as tf
tf.logging.set_verbosity(tf.logging.ERROR)
print(tf.__version__)

1.9.0-rc0


### Step 1: Generate sample equations

In [0]:
class CharacterTable(object):
    """Given a set of characters:
    + Encode them to a one hot integer representation
    + Decode the one hot integer representation to their character output
    + Decode a vector of probabilities to their character output
    """
    def __init__(self, chars):
        """Initialize character table.

        # Arguments
            chars: Characters that can appear in the input.
        """
        self.chars = sorted(set(chars))
        self.char_indices = dict((c, i) for i, c in enumerate(self.chars))
        self.indices_char = dict((i, c) for i, c in enumerate(self.chars))

    def encode(self, C, num_rows):
        """One hot encode given string C.

        # Arguments
            num_rows: Number of rows in the returned one hot encoding. This is
                used to keep the # of rows for each data the same.
        """
        x = np.zeros((num_rows, len(self.chars)))
        for i, c in enumerate(C):
            x[i, self.char_indices[c]] = 1
        return x

    def decode(self, x, calc_argmax=True):
        if calc_argmax:
            x = x.argmax(axis=-1)
        return ''.join(self.indices_char[x] for x in x)


In [0]:
class colors:
    ok = '\033[92m'
    fail = '\033[91m'
    close = '\033[0m'

In [58]:
#@title Model & Dataset Parameters
# Parameters for the model and dataset.
global DIGIT_LEN
global ITERATIONS
global HIDDEN_SIZE
global BATCH_SIZE
global RNN_TYPE
global EPOCHS
global ACTIVATION

# Form fields
ARITH_OPERATION = "ADD" #@param ["ADD", "SUB", "MUL", "DIV"]
RNN_TYPE = "Simple" #@param ["Simple", "GRU", "LSTM"]
ACTIVATION = "softmax" #@param ["softmax", "softplus", "sigmoid", "hard_sigmoid", "elu", "selu", "softsign", "relu", "tanh", "linear"]
TRAINING_SIZE = 50000 #@param {type:"slider", min:100, max:100000, step:100}
ITERATIONS = 20 #@param {type:"slider", min:1, max:40, step:1}
EPOCHS = 1 #@param {type:"slider", min:1, max:20, step:1}
HIDDEN_SIZE = 128 #@param {type:"slider", min:4, max:256, step:4}
BATCH_SIZE = 128 #@param {type:"slider", min:4, max:256, step:4}

OPS = {"ADD":"+", "SUB":"-", "MUL":"*", "DIV":"/"}
OP = OPS[ARITH_OPERATION]
DIGITS = 3
REVERSE = False
# Maximum length of input is 'int + int' (e.g., '345+678'). Maximum length of
# int is DIGITS.
MAXLEN = DIGITS + 1 + DIGITS

# All the numbers, plus sign and space for padding.

chars = '0123456789' + OP + ' '
ctable = CharacterTable(chars)

questions = []
expected = []
seen = set()
print('Generating data...')
while len(questions) < TRAINING_SIZE:
    f = lambda: int(''.join(np.random.choice(list('0123456789'))
                    for i in range(np.random.randint(1, DIGITS + 1))))
    a, b = f(), f()
    # Skip any addition questions we've already seen
    # Also skip any such that x+Y == Y+x (hence the sorting).
    key = tuple(sorted((a, b)))
    if key in seen:
        continue
    seen.add(key)
    # Pad the data with spaces such that it is always MAXLEN.
    if OP == "/" and b == 0:
      continue
    q = ('{}' + OP + '{}').format(a, b)
    query = q + ' ' * (MAXLEN - len(q))
    ans = str(int(eval(str(a) + OP + str(b))))
    # Answers has a maximum size regarding selected OP
    # => ADD: (DIGITS + 1)
    # => SUB: (DIGITS + 1)
    # => MUL: (DIGITS * 2)
    # => DIV: (DIGITS)
    DIGIT_LENS = {"ADD":DIGITS + 1, "SUB":DIGITS + 1, "MUL":DIGITS * 2, "DIV":DIGITS}
    DIGIT_LEN = DIGIT_LENS[ARITH_OPERATION]
    ans += ' ' * (DIGIT_LEN - len(ans))
    if REVERSE:
        # Reverse the query, e.g., '12+345  ' becomes '  543+21'. (Note the
        # space used for padding.)
        query = query[::-1]
    questions.append(query)
    expected.append(ans)
print('Total addition questions:', len(questions))

Generating data...
Total addition questions: 50000


In [59]:
questions[0]

'0+4    '

In [60]:
print('Vectorization...')
x = np.zeros((len(questions), MAXLEN, len(chars)), dtype=np.bool)
y = np.zeros((len(questions), DIGIT_LEN, len(chars)), dtype=np.bool)
for i, sentence in enumerate(questions):
    x[i] = ctable.encode(sentence, MAXLEN)
for i, sentence in enumerate(expected):
    y[i] = ctable.encode(sentence, DIGIT_LEN)


Vectorization...


In [61]:
len(x[0])

7

In [62]:
len(questions[0])

7

In [63]:
questions[0]

'0+4    '

In [64]:
x[0]

array([[False, False,  True, False, False, False, False, False, False,
        False, False, False],
       [False,  True, False, False, False, False, False, False, False,
        False, False, False],
       [False, False, False, False, False, False,  True, False, False,
        False, False, False],
       [ True, False, False, False, False, False, False, False, False,
        False, False, False],
       [ True, False, False, False, False, False, False, False, False,
        False, False, False],
       [ True, False, False, False, False, False, False, False, False,
        False, False, False],
       [ True, False, False, False, False, False, False, False, False,
        False, False, False]])

In [65]:
y[0]

array([[False, False, False, False, False, False,  True, False, False,
        False, False, False],
       [ True, False, False, False, False, False, False, False, False,
        False, False, False],
       [ True, False, False, False, False, False, False, False, False,
        False, False, False],
       [ True, False, False, False, False, False, False, False, False,
        False, False, False]])

In [66]:
expected[0]

'4   '

In [0]:
# Shuffle (x, y) in unison as the later parts of x will almost all be larger
# digits.
indices = np.arange(len(y))
np.random.shuffle(indices)
x = x[indices]
y = y[indices]

### Step 2: Training/Validation Split

In [46]:
# Explicitly set apart 10% for validation data that we never train over.
split_at = len(x) - len(x) // 10
(x_train, x_val) = x[:split_at], x[split_at:]
(y_train, y_val) = y[:split_at], y[split_at:]

print('Training Data:')
print(x_train.shape)
print(y_train.shape)

print('Validation Data:')
print(x_val.shape)
print(y_val.shape)

Training Data:
(45000, 7, 12)
(45000, 4, 12)
Validation Data:
(5000, 7, 12)
(5000, 4, 12)


### Step 3: Create Model

In [47]:
# input shape: 7 digits, each being 0-9, + or space (12 possibilities)
MAXLEN, len(chars)

(7, 12)

In [48]:
from keras.models import Sequential
from keras import layers

# Select RNN Type by param RNN_TYPE
RNN = {"Simple":layers.SimpleRNN, "GRU":layers.GRU, "LSTM":layers.LSTM}[RNN_TYPE]

print('Build model...')
model = Sequential()
# encoder: simply encode the same input 4 times 
model.add(RNN(units=HIDDEN_SIZE, input_shape=(MAXLEN, len(chars))))
model.add(layers.RepeatVector(DIGIT_LEN))

# decoder: have 4 temporal outputs one for each of the digits of the results
# return_sequences=True tells it to keep all 4 temporal outputs, not only the final one (we need all four digits for the results)
model.add(RNN(units=HIDDEN_SIZE, return_sequences=True))

model.add(layers.Dense(name='classifier', units=len(chars), activation=ACTIVATION))

model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])
model.summary()

Build model...
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_3 (SimpleRNN)     (None, 128)               18048     
_________________________________________________________________
repeat_vector_2 (RepeatVecto (None, 4, 128)            0         
_________________________________________________________________
simple_rnn_4 (SimpleRNN)     (None, 4, 128)            32896     
_________________________________________________________________
classifier (Dense)           (None, 4, 12)             1548      
Total params: 52,492
Trainable params: 52,492
Non-trainable params: 0
_________________________________________________________________


In [49]:
model.predict(np.array([x_val[0]]))

array([[[0.05583213, 0.09151785, 0.05079578, 0.05850346, 0.1298858 ,
         0.08019083, 0.08559722, 0.10721804, 0.09004891, 0.07676934,
         0.0914418 , 0.08219887],
        [0.05219937, 0.06319936, 0.05023049, 0.04522064, 0.14513569,
         0.06801919, 0.08943921, 0.10123521, 0.08815693, 0.07558998,
         0.10402995, 0.11754397],
        [0.06358391, 0.08340737, 0.05452808, 0.03097076, 0.12591226,
         0.06890775, 0.10449225, 0.09726649, 0.10291927, 0.09695347,
         0.06166456, 0.10939384],
        [0.04836524, 0.05777589, 0.05426113, 0.04001648, 0.1741874 ,
         0.05270612, 0.08876176, 0.10401142, 0.08225408, 0.10043459,
         0.08007123, 0.11715466]]], dtype=float32)

In [50]:
model.predict_classes(np.array([x_val[0]]))

array([[4, 4, 4, 4]])

### Step 4: Train

In [0]:
# Train the model each generation and show predictions against the validation
# dataset.
for iteration in range(1, ITERATIONS + 1):
    print()
    print('-' * 50)
    print('Iteration', iteration)
    model.fit(x_train, y_train,
              batch_size=BATCH_SIZE,
              epochs=EPOCHS,
              validation_data=(x_val, y_val))
    # Select 10 samples from the validation set at random so we can visualize
    # errors.
    for i in range(10):
        ind = np.random.randint(0, len(x_val))
        rowx, rowy = x_val[np.array([ind])], y_val[np.array([ind])]
        preds = model.predict_classes(rowx, verbose=0)
        q = ctable.decode(rowx[0])
        correct = ctable.decode(rowy[0])
        guess = ctable.decode(preds[0], calc_argmax=False)
        print('Q', q[::-1] if REVERSE else q, end=' ')
        print('T', correct, end=' ')
        if correct == guess:
            print(colors.ok + '☑' + colors.close, end=' ')
        else:
            print(colors.fail + '☒' + colors.close, end=' ')
        print(guess)

In [0]:
x_val[0]

In [0]:
model.predict(np.array([x_val[0]]))

In [0]:
model.predict_classes(np.array([x_val[0]]))